---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: f8515cee6a094f3f7f6821eb708d3a4ef68fd7a4
    app.quarkus.io/build-timestamp: 2024-09-22 - 09:43:17 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: car-fleet
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: car-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: car-fleet
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: f8515cee6a094f3f7f6821eb708d3a4ef68fd7a4
        app.quarkus.io/build-timestamp: 2024-09-22 - 09:43:17 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: car-fleet
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          name: car-fleet
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
