---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: f8515cee6a094f3f7f6821eb708d3a4ef68fd7a4
    app.quarkus.io/build-timestamp: 2024-09-22 - 09:43:17 +0000
  labels:
    app.kubernetes.io/name: car-fleet
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: car-fleet
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: car-fleet
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
